using System.Text.Json;

namespace Meziantou.Prebuilt;

/// <summary>The files of a release, as generated by scripts/New-PrebuiltManifest.ps1.</summary>
internal sealed class PrebuiltManifest
{
    internal const string EmbeddedResourceName = "Meziantou.Prebuilt.prebuilt-tools.json";

    private static readonly Lazy<PrebuiltManifest?> EmbeddedManifest = new(LoadEmbedded);

    private PrebuiltManifest(string releaseVersion, Uri downloadBaseUrl, IReadOnlyList<PrebuiltManifestEntry> entries)
    {
        ReleaseVersion = releaseVersion;
        DownloadBaseUrl = downloadBaseUrl;
        Entries = entries;
    }

    public string ReleaseVersion { get; }
    public Uri DownloadBaseUrl { get; }
    public IReadOnlyList<PrebuiltManifestEntry> Entries { get; }

    public static bool IsEmbedded => EmbeddedManifest.Value is not null;

    public static PrebuiltManifest Embedded => EmbeddedManifest.Value ?? throw new InvalidOperationException($"The assembly does not contain the '{EmbeddedResourceName}' resource. Official Meziantou.Prebuilt packages always embed it; local builds must pass -p:PrebuiltManifestPath=<path>.");

    private static PrebuiltManifest? LoadEmbedded()
    {
        using var stream = typeof(PrebuiltManifest).Assembly.GetManifestResourceStream(EmbeddedResourceName);
        return stream is null ? null : Load(stream);
    }

    public static PrebuiltManifest Load(Stream stream)
    {
        var model = JsonSerializer.Deserialize(stream, PrebuiltManifestJsonContext.Default.PrebuiltManifestModel)
            ?? throw new InvalidDataException("The prebuilt manifest is empty.");
        return FromModel(model);
    }

    public static PrebuiltManifest Parse(string json)
    {
        var model = JsonSerializer.Deserialize(json, PrebuiltManifestJsonContext.Default.PrebuiltManifestModel)
            ?? throw new InvalidDataException("The prebuilt manifest is empty.");
        return FromModel(model);
    }

    private static PrebuiltManifest FromModel(PrebuiltManifestModel model)
    {
        var releaseVersion = Required(model.ReleaseVersion, "releaseVersion");
        var downloadBaseUrlText = Required(model.DownloadBaseUrl, "downloadBaseUrl");
        if (!downloadBaseUrlText.EndsWith('/'))
        {
            downloadBaseUrlText += '/';
        }

        if (!Uri.TryCreate(downloadBaseUrlText, UriKind.Absolute, out var downloadBaseUrl))
            throw new InvalidDataException($"The prebuilt manifest 'downloadBaseUrl' is not an absolute URL: '{model.DownloadBaseUrl}'.");

        var entries = new List<PrebuiltManifestEntry>();
        foreach (var tool in model.Tools ?? [])
        {
            var fileName = Required(tool.FileName, "tools[].fileName");
            var sha256 = Required(tool.Sha256, "tools[].sha256");
            if (sha256.Length != 64 || !sha256.All(char.IsAsciiHexDigit))
                throw new InvalidDataException($"The prebuilt manifest has an invalid SHA-256 for '{fileName}': '{sha256}'.");

            if (tool.Size < 0)
                throw new InvalidDataException($"The prebuilt manifest has an invalid size for '{fileName}': {tool.Size}.");

            entries.Add(new PrebuiltManifestEntry(
                Name: Required(tool.Name, "tools[].name"),
                RuntimeIdentifier: Required(tool.RuntimeIdentifier, "tools[].runtimeIdentifier"),
                Version: Required(tool.Version, "tools[].version"),
                FileName: fileName,
                Size: tool.Size,
#pragma warning disable CA1308 // Hex checksums are displayed and stored in lowercase
                Sha256: sha256.ToLowerInvariant(),
#pragma warning restore CA1308
                DownloadUrl: new Uri(downloadBaseUrl, Uri.EscapeDataString(fileName))));
        }

        return new PrebuiltManifest(releaseVersion, downloadBaseUrl, entries);

        static string Required(string? value, string name)
        {
            if (string.IsNullOrWhiteSpace(value))
                throw new InvalidDataException($"The prebuilt manifest is missing '{name}'.");

            return value;
        }
    }
}
